
services:
    scraper:
      build: .
      env_file:
        - ml.env
      ports:
        - '5000:5000'
      volumes:
        - '.:/app'
      expose:
        5000
  
  
  
    ml:
      build: ./ml
      depends_on:
        - scraper
      env_file:
        - calculator.env
      ports:
        - '5001:5000'
      volumes:
        - './ml:/app'
      expose:
        5001
  
#   networks:
#     my_network:
#       driver: bridge