version: '3.5'
services:

  # frontend:
    # front:
      # container_name: front
      # build: ./front/
      # ports:
        # - "80:200"
      # networks:
  scraper:
    container_name: scraper
    restart: always
    build: ./scraper/
    ports:
      - "5000:5000"
    networks:
      - backend

  ml:
    container_name: ml
    restart: always
    build: ./ml/
    ports:
      - "5001:5001"
    networks:
      - backend
 
  mongo:
    container_name: mongo
    restart: always
    build: ./yt_data/
    ports:
      - "27017:27017"
    networks:
      - backend

networks: 
    backend: