version: '3.5'
services:
  front:
    container_name: front_tmp
    restart: always
    build: ./front_tmp/
    ports:
      - "5002:5002"

  scraper:
    container_name: scraper
    restart: always
    build: ./scraper/
    ports:
      - "5000:5000"

  ml:
    container_name: ml
    restart: always
    build: ./ml/
    ports:
      - "5001:5001"
 
  mongodb:
    container_name: mongodb
    restart: always
    build: ./yt_data/
    ports:
      - "27017:27017"
