version: '3'
services:
  scrapper:
    container_name: scrapper
    restart: always
    build: ./scrapper/
    ports:
      - '5333:5333'
    # links:
      # - mongo
  front:
    container_name: node
    restart: always
    build: ./front/
    ports:
      - '80:5333'
    links:
      - scrapper
    ## volumes:
    ##    - .:/code
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports:
  #     - '27017:27017'


